name: auto_size_text_pk
description: Flutter widget that automatically resizes text to fit perfectly within its bounds.
version: 3.0.0-nullsafety.1
homepage: https://github.com/iampawan/auto_size_text

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.24.0-0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.10.0-nullsafety.3
